name: Send emails
on: 
  push:

env:
  APIKEY: ${{ secrets.APIKEY }}    

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push report
        run: |
          curl -s --user 'api:${{ env.APIKEY }}'  \
          https://api.mailgun.net/v3/sandbox578929e814e844ed920095209f77b678.mailgun.org/messages  \
          -F from='Domain Expiration Automation <postmaster@sandbox.mgsend.net>'  \
          -F to='Thibault DUPONCHELLE <thibault@deriv.com>'  \
          -F subject='Report domains expiration'  \
          -F text="`cat report.txt`"
